### ISSUE TITLE
ModuleNotFoundError: No module named 'commands'

### ISSUE THREAD

**Issue by creboy** [Linux-Doc/zimuzu-action#2]
Run ACCOUNT='***'
***
***
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'commands'
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'commands'
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'commands'
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'commands'
{"status":0,"info":"\u5e10\u53f7\u4e0d\u80fd\u4e3a\u7a7a\u3002","data":true}
{"status":4001,"info":"","data":""}
2020-12-24 09:00:40 人人钻:

**Comment by JoJo720** [comment]
稳定运行几个月了，无需修改维护.
<img width="1140" alt="2020-12-25-221211" src="https://user-images.githubusercontent.com/33677811/103136794-890e8600-46fe-11eb-8670-7997c498087e.png">
<img width="1224" alt="2020-12-25-221240" src="https://user-images.githubusercontent.com/33677811/103136797-8c097680-46fe-11eb-8373-20f30bd00064.png">
